name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - name: Run tests
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
          RUN_INTERVAL: "false"
        run: npm test
      - name: Publish image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hakanensari/country
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
